site_name: Packaging Lab
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
repo_url: https://github.com/epassaro/packaginglab
repo_name: epassaro/packaginglab

nav:
  - Introduction: index.md
  - Packaging Systems:
      - AppImage: appimage.md
      - Flatpak: flatpak.md
      - conda-forge: conda-forge.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true